### ISSUE TITLE
where is the SeesawLoss2？

### ISSUE THREAD

**Issue by c-dafan** [ShaneShen/BDANet-Building-Damage-Assessment#3]
The losses.py of [xview2_1st_place_solution](https://github.com/vdurnov/xview2_1st_place_solution) doesn't have the SeesawLoss2. How can I get the SeesawLoss2?

**Comment by ShaneShen** [comment]
Hi, maybe you can read this https://arxiv.org/abs/2008.10032. Hope can help you
