### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Daisy-7** [ShaneShen/BDANet-Building-Damage-Assessment#4]
Hi, it is a nice work.  When I run the code, something goes wrong:
1. Where can I find the antialias file? 
`from .antialias import Downsample as downsamp`
2. Do you try end to end training mode rather than two-stage? I'm curious about the effect of them. Which one is better?

**Comment by ShaneShen** [comment]
1. You can check the https://github.com/vdurnov/xview2_1st_place_solution. The antialias is included.
2. I did not due the GPU limited. I think end to end training is a good idea.
