### ISSUE TITLE
BDANet Model

### ISSUE THREAD

**Issue by erenberkedinc** [ShaneShen/BDANet-Building-Damage-Assessment#6]
I want to recreate the model in the article you wrote, "BDANet: Multiscale Convolutional Neural Network with Cross-directional 
Attention for Building Damage Assessment from Satellite Images", using the codes on github. However, I could not see the model part you mentioned as Cross Directional Attention in any of the models you created. I couldn't find the code of the model you mentioned in the article on github. If there is another version of the code, etc., can you share it with me? Or is there something I missed? I will be grateful if you could help me.

**Comment by ShaneShen** [comment]
Hi, sorry for late response. As I have graduated for over two years, the original project is missing. The Cross Directional Attention module is quite simple, and I have rewritten a Channel Feature Fusion for your reference (FuseResBlock in modelMscale.py Line 100).  A Spatial Feature Fusion is similar. 
Hope helpful to you.
